services:
  - type: web
    name: compare-it-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    plan: free
    region: singapore  # You can change this to your preferred region 